### ISSUE TITLE
[Request] Support for using self-hosted server

### ISSUE THREAD

**Issue by ehsandeep** [wdahlenburg/interactsh-collaborator#10]
Many of the users running self-hosted interactsh server will be able to utilize this burp extension for manual testing.

**Comment by wdahlenburg** [comment]
Hi @ehsandeep I believe this feature has always been supported via the configuration tab. I run my own interactsh server and am able to set the server, port, use of TLS, and itoken.

Do you have any other details that may prevent others from using a self-hosted instance? I just verified that I was able to register and receive events on a version 1.0.2 interactsh server.

**Comment by ehsandeep** [comment]
@wdahlenburg, my bad. For testing purposes I had the older version of the extension installed. This is indeed supported and works well in the latest version.
