### ISSUE TITLE
server can't find xxxxxxx.interact.sh: SERVFAIL

### ISSUE THREAD

**Issue by MHR890** [wdahlenburg/interactsh-collaborator#12]
I just installed the interact.sh extension to my burp suite. Whenever I am generating a interact.sh url and doing a nslookup ...I am getting this things 

Non-authoritative answer:
Name:	xxxxl.interact.sh
Address: xx.xxx.xx.xxx
** server can't find xxxx.interact.sh: SERVFAIL

Also these are the ouputs that I am getting 

Starting Interactsh Collaborator!
Generating new Interactsh client
New domain is: cd8d7o6kefpgb695q2kgviuzsvrsdavbl.interact.sh
Response cannot be null
Error registering client

**Comment by wdahlenburg** [comment]
Hi @MHR890. Some DNS servers have sinkholed the original interact.sh domain, which prevents some users from resolving to the real IP depending on what DNS server is in use.

Project Discovery added several other domains that can be used:

- oast.pro
- oast.live
- oast.site
- oast.online
- oast.fun
- oast.me

The extension allows you to change the configured server that is used. Try one of these out and see if you are able to get an OOB subdomain.

**Comment by MHR890** [comment]
Hello @wdahlenburg ...The problem is fixed now. BTW, it's a great tool.  Thanks for giving me a reply. You are too kind. I can not express my appreciation. Please accept my deepest thanks.

**Comment by faisalrathore93** [comment]
seems non of the hosts are working at the moment.

Starting Interactsh Collaborator!
Generating new Interactsh client
New domain is: cglpa9gjseq75upmmch0ovgbldsnvddcf.oast.me
java.lang.RuntimeException: java.net.UnknownHostException: oast.me
Error registering client

Generating new Interactsh client
New domain is: cglpaq8jseq75upmmchgzagaxfisfksgt.oast.live
java.lang.RuntimeException: java.net.UnknownHostException: oast.live
Error registering client

Generating new Interactsh client
New domain is: cglpbbgjseq75upmmci0cyoqiehjhhyrw.oast.online
java.lang.RuntimeException: java.net.UnknownHostException: oast.online
Error registering client

Generating new Interactsh client
New domain is: cglpbn8jseq75upmmcigvxdgxglwymixt.oast.pro
java.lang.RuntimeException: java.net.UnknownHostException: oast.pro
Error registering client

Generating new Interactsh client
New domain is: cglpc9gjseq75upmmcj0pgzeipulknbut.oast.fun
java.lang.RuntimeException: java.net.UnknownHostException: oast.fun
Error registering client

Generating new Interactsh client
New domain is: cglpda8jseq75upmmcjgpntuuupxcqjet.oastify.com
A JSONObject text must begin with '{' at 1 [character 2 line 1]
A JSONObject text must begin with '{' at 1 [character 2 line 1]
A JSONObject text must begin with '{' at 1 [character 2 line 1]
