### ISSUE TITLE
InteractSH Collaborator not showing logs

### ISSUE THREAD

**Issue by jjmuriel** [wdahlenburg/interactsh-collaborator#13]
Hi, my problem is that there is not logs on this window:
![image](https://user-images.githubusercontent.com/17131600/204923846-2701fb69-aef0-48f0-99b0-a1c5198fde31.png)
This is my configuration:
![image](https://user-images.githubusercontent.com/17131600/204923924-a92f7c56-bcdf-4221-9b42-85f4e4c217c8.png)

and this is the output on Extensions window:
![image](https://user-images.githubusercontent.com/17131600/204924176-96b3ec49-8b81-4d7e-bb44-d6729b619dfe.png)
Any ideas? I'm using Burp Suite CE v2022.9.6 build 17218 and  InteractSH Collaborator Extension v1.0.1   Thanks.

**Comment by wdahlenburg** [comment]
Hi @jjmuriel. Can you test out one of the servers on https://github.com/wdahlenburg/interactsh-collaborator/issues/12? `oastify.com` is the default domain for BurpSuite's collaborator, which uses a different mechanism than Interact.sh servers

**Comment by jjmuriel** [comment]
Thank you.  With this server the extension works fine.
